public static class jadenSmithFakes
{
    private static string[][] fakeQuotes = {
        new string[] { "Shout Out To My Guy Zac Efron" },
        new string[] { "Green White And Blue Make Dreams Come True." },
        new string[] { "When I Die. Then You Will Realize" },
        new string[] { "If A Cup Cake Falls From A Tree How Far Away Will It Be From Down. #Jupiter" },
        new string[] { "When The First Animal Went Extinct That Should've Bin A Sign." },
        new string[] { "A lot Of My Tweets Will Come True In 2018" },
        new string[] { "Education Is Rebellion." },
        new string[] { "I Honestly Love When People Hate Even When There Close To You." },
        new string[] { "You Think You Get It. YOU DONT YOU DONT YOU DONT!!!!!!!" },
        new string[] { "The Head Of The Sphinx Will Fall Off In The Near Future." },
        new string[] { "I Got 3 Instagram Followers" },
        new string[] { "The Biggest Flex Anyone Will Ever Have Is Dying." },
        new string[] { "I Am Not A Human And I Don't Speak English" },
        new string[] { "\"the displacement from zero at zero time of a body undergoing simple harmonic motion.\"" },
        new string[] { "I Only Apply To The Sixth Amendment" },
        new string[] { "Reading Is My Passion And My Escape Since I Was 5 Years Old. Overall, Children Don't Realize The Magic That Can Live Inside Their Own Heads. Better Even Then Any Movie." },    
        new string[] { "Once All 100% Is Neglected You Have A Citizen. A Walking Zombie Who Criticizes Every Thing They See. Have Fun Its A Really Awesome Place." },
        new string[] { "The Moment That Truth Is Organized It Becomes A Lie." },
        new string[] { "If Newborn Babies Could Speak They Would Be The Most Intelligent Beings On Planet Earth" },
        new string[] { "Unawareness Is The Only Sin, And If You Were Aware You Would Know." },
        new string[] { "Me: Hey Wanna Talk About The Economic And Political State Of World Together. Girl: Nah Me: Ok Cool" },
        new string[] { "We Need To Stop Teaching The Youth About The Past And Encourage Them To Change The Future" },
        new string[] { "I'm Glad That Our Distance Makes Us Witness Ourselves From A Different Entrance." },
        new string[] { "Don't Argue With Anybody About What Color The Sky Is." },
        new string[] { "People Tell Me To Smile I Tell Them The Lack Of Emotion In My Face Doesn't Mean I'm Unhappy" },
        new string[] { "\"Hey Are You Jaden Can I Have A Picture With You\" No Cause I'm Super Sad But We Can Sit And Talk." },
        new string[] { "Pay Attention To The Numbers In Your Life They Are Vastly Important." },
        new string[] { "Why Is It Always 3 WHY IS IT ALWAYS 3!!!!!" },
        new string[] { "I Encourage You All To Unfollow Me So I Can Be Left With The People Who Actually Appreciate Philosophy And Poetry. #CoolTapeVol2" },
        new string[] { "I'm Here If You Need A Fellow Insane Person To Talk To. But I'm Seriously Here Not Like One Of Those I'm Here For You's That Everybody Says." },
        new string[] { "Don't Worry Bae I'll Talk To You About SpaceTime Over FaceTime." },
        new string[] { "REAL TALK: Sometimes I Am Scared By All My Wisdom. Jaden Out." },
        new string[] { "Water In The Eyes And Alcohol In The Eyes Are Pretty Much The Same I Know This From First Hand Experience." },
        new string[] { "como os espelhos podem ser reais se nossos olhos não são reais" },
        new string[] { "How Can Mirrors Be Real If Our Eyes Aren't Real" },
        new string[] { "Everybody Get Off Your Phones And Go Do What You Actually Wanna Do" },
        new string[] { "You Do Not Know Who You Are Or Why Your Here So When You See Someone Who Dose The Society Comes Together As A Whole And Destroys Them." },
        new string[] { "Pop Changes Week To Week, Month To Month. But Great Music Is Like Literature." },
        new string[] { "If It's Lit, It's Truly Lit" },
        new string[] { "People Use To Ask Me What Do You Wanna Be When You Get Older And I Would Say What A Stupid Question The Real Question Is What Am I Right Now" },
        new string[] { "I Will Always Give You The Truth I Will Never Lie To You In My music If You Cant Handle My Feelings And Emotions Please Unfollow Me" },
        new string[] { "I Just Like Showing Pretty Girls A Good Time Weather I'm Physically There Or Not Doesn't Matter." },
        new string[] { "All The Rules In This World Were Made By Someone No Smarter Than You. So Make Your Own" },
        new string[] { "I Should Just Stop Tweeting, The Human Consciousness Must Raise Before I Speak My Juvenile Philosophy. Shouts Out To @TIME" },
        new string[] { "School Is The Tool To Brainwash The Youth." },
        new string[] { "Females Are Amazing." },
        new string[] { "A Little Girl Just Asked Me If I Was Willow Smith I Humbly Said Yes And Took A Selfie." },
        new string[] { "When You Party I'm On The Treadmill,When You Sleep I'm On The Treadmill, When I Tweet I'm On TheTreadmill. Remember This" },
        new string[] { "What Is The Definition Of \"Light\"?" },
        new string[] { "Trees Are Never Sad Look At Them Every Once In Awhile They're Quite Beautiful" },
        new string[] { "If A Book Store Never Runs Out Of A Certain Book, Dose That Mean That Nobody Reads It, Or Everybody Reads It" },
        new string[] { "Dying Is MainStream #MONEY" },
        new string[] { "Every 7 Years Your Body Is Completely Replaced With Entirely New Cells So Just Because You Look The Same Doesn't Mean You Are." },
        new string[] { "The More Time You Spend Awake The More Time You Spend Asleep." },
        new string[] { "Here's The Deal We Can All Follow Christ,Buddha,Krishna You Choose. Or. We Can Become Them." },
        new string[] { "If Everybody In The World Dropped Out Of School We Would Have A Much More Intelligent Society" },
        new string[] { "I Don't Want You Guys To Think Because I Was Born In America That I Speak And Abide By English Grammar. I Speak Jaden, Indefinitely." },
        new string[] { "Most Trees Are Blue" },
        new string[] { "You Can Discover Everything You Need To Know About Everything By Looking At Your Hands" },
        new string[] { "I Hope It Doesn't Take For Me To Die For You To See What I Do For You" },
        new string[] { "If I Were White And Not Will Smith's \"\"\"\"\"SILLY\"\"\"\"\" Son I Would Be The Most Respected Philosopher Of Our And All Time." },
        new string[] { "To The Artist Of This Coming Generation And Of The Renaissance. The People That Truly Understand Your Art are The People Who Don't Comment" },
        new string[] { "People Think A RelationShip Makes You Whole, That It's Two 50%'s Coming Together To Make 100% When It Should Be Two 100%'s Making 200%•••" },
        new string[] { "Stop Gossiping Reflect Internally You Will Find Yourself A Neglected Part Of Your Self." },
        new string[] { "There Is No World Outside Us. The World Is, In Fact, Our Collective Projections Of Love And Fear, Hopes And Conflicts. In Taking Responsibility For Our Own Thoughts And Feelings, We play Our Part In The Healing Of The World." },
        new string[] { "If I Die In My Flannel Will You Write My Poems On Tyler's 5 Panels And Jesusus Sandals This Plane Is Just To Much To Handle." },
        new string[] { "Girls Don't Like Gentlemen" },
        new string[] { "Ill Never Forget The Blogs That Believed In Me Since The Begging." },
        new string[] { "Either I Lie To You Or We Cry Together" },
        new string[] { "Umm Who Has The Floss" },
        new string[] { "You Taught Me How To Play The Piano But Have Never Heard Me." },
        new string[] { "Im Not A Person" },
        new string[] { "If I Wanna Wear A Dress, Then I Will, And That Will Set The New Wave... -JADEN SMITH #ICON" },
        new string[] { "Once You Go In You Always Come Out Alive" },
        new string[] { "Female Energy" },
        new string[] { "When You Live Your Whole Life In A Prison Freedom Can Be So Dull." },
        new string[] { "The Great Gatsby Is One Of The Greatest Movies Of All Time, Coachella." },
        new string[] { "If There Is Bread Winners, There Is Bread Losers. But You Can't Toast What Isn't Real. #BreadPeopleLives" },
        new string[] { "Jealousy Just Reassures Your Love." },
        new string[] { "The More Intelligent Somebody Becomes The More I Fall In Love With Them." },
        new string[] { "I Just Scrolled Through My Tweets And \"I\" Started Laughing." },
        new string[] { "Luke. Who Has The Trident" },
        new string[] { "You Would Have To Eat 5 Apples Today To Get The Same Nutritional Value As An Apple From 1950. #Fallow" },
        new string[] { "\"It's Your Birthday\" Mateo Said. I Didn't Respond. \"Are You Not Excited To Be 15\" He Asked. Reading My Book I Uttered \"I Turned 15 Long Ago\"" },
        new string[] { "I Build Pyramids Constantly" },
        new string[] { "I Scare People Away" },
        new string[] { "Anyone Born On This Planet Should Have A Planetary Citizenship Enabling Them To Freely Explore There Home" },
        new string[] { "If You Focus On Success, You'll Have Stress. But If You Pursue Excellence, Success Will Be Guaranteed." },
        new string[] { "Lately People Call Me Scoop Life" },
        new string[] { "I Only Skate When I Have Emotional Trauma" },
        new string[] { "Commit To Love Not To People, Commit To Happiness Because When You Commit To People The Love Leaves And You Are Forced To Stay." },
        new string[] { "Either I Only Have One Pair Of Shoes Or Every Pair You Choose." },
        new string[] { "I've Bin Drinking Distilled Water For So Long That When I Drink Normal Water It Feels Like I'm Swallowing Huge Chunks Of Aluminum." },
        new string[] { "I'm Here For You. We're About To Flip Things Around" },
        new string[] { "If I Had A Nickel For Every Time I've Cried In The Back Of An Uber, I Would Have Another Pair Of Yeezy's." },
        new string[] { "I Watch Twilight Every Night" },
        new string[] { "There Is No Nutrients In Our Food Anymore Or In Our Soil OR IN OUR WATER" },
        new string[] { "Don't Tell Me You Cried Cause I Know That You Didn't" },
        new string[] { "You Must Not Know Fashion" },
    };
}